# NumPy(Part-01):

In [1]:
#import numpy library
import numpy as np

In [3]:
# Array Fundamental:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [4]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4]])

In [5]:
a2.shape

(1, 5)

In [6]:
a2.size

5

In [7]:
a3 = a[:, np.newaxis]
a3


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [8]:
a3.shape

(5, 1)

In [9]:
a3.size

5

In [10]:
a = np.array([1, 2 ,3, 4, 5,  6])
b = np.array([5, 6, 7, 8, 9, 1])
print(a)

[1 2 3 4 5 6]


In [11]:
print(b)

[5 6 7 8 9 1]


In [12]:
b.shape

(6,)

In [13]:
b.dtype

dtype('int64')

In [15]:
array = np.array((3, 4))
array


array([3, 4])

In [16]:
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
zeros = np.zeros((5, 2))

In [18]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [22]:
full = np.full((5,3), 4)
full

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [24]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
identity.dtype

dtype('float64')

In [26]:
type(identity)

numpy.ndarray

In [27]:
len(identity)

4

In [28]:
identity.ndim

2

In [29]:
identity.size

16

In [30]:
# Operators (+, -, /, *)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

In [32]:
d = a-b
d

array([-3, -3, -3])

In [34]:
f = a/b
f

array([0.25, 0.4 , 0.5 ])

In [35]:
k = a*b
k

array([ 4, 10, 18])

In [36]:
k = a**2
k

array([1, 4, 9])

In [39]:
#Empty Array:
empty = np.empty(2)
empty

array([5.43230922e-312, 7.29112202e-304])

In [40]:
n = np.empty((4, 5))
n

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.45060607e-308, 1.11260619e-306],
       [1.33509117e-306, 1.42420209e-306, 9.34609111e-307,
        1.11256817e-306, 1.06811422e-306],
       [1.42417221e-306, 1.11260619e-306, 8.90094053e-307,
        1.86919378e-306, 1.06809792e-306],
       [1.37962456e-306, 1.69111861e-306, 1.78020169e-306,
        1.37961777e-306, 7.56599807e-307]])

In [41]:
print(empty[0])

5.432309224876e-312


In [43]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [47]:
#Even Numbers:
x = np.arange(0, 23, 2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [48]:
#Odd Numbers:
y = np.arange(1, 23, 2)
y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [49]:
# A Specific range:
u = np.arange(0, 23, 5)
u

array([ 0,  5, 10, 15, 20])

In [50]:
#A line space:
lin = np.linspace(0, 20, num=4)
lin

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [51]:
# By indicating the DataType:
z = np.arange(5, dtype=np.int64)
z

array([0, 1, 2, 3, 4])

In [52]:
z.dtype

dtype('int64')

In [53]:
x = np.ones(5, dtype=np.float32)
x

array([1., 1., 1., 1., 1.], dtype=float32)

In [54]:
np.sort(x)

array([1., 1., 1., 1., 1.], dtype=float32)

In [55]:
arr = np.array([2, 4, 6, 7, 1, 5])
arr

array([2, 4, 6, 7, 1, 5])

In [56]:
# Sorting of Array
np.sort(arr)

array([1, 2, 4, 5, 6, 7])

In [58]:
# Concatenate of Array:
a = np.array([1, 2, 3, 4, 5])
c = np.array([3, 4, 5, 6, 7])
d = np.concatenate((a, c))
d

array([1, 2, 3, 4, 5, 3, 4, 5, 6, 7])

In [72]:
s = np.array([[[12, 3, 1]], [[2, 3, 4]],[[5, 6,7]]])
k = np.array([[2,3, 5]])
f = np.concatenate((s, k[:, np.newaxis, :]))
f


array([[[12,  3,  1]],

       [[ 2,  3,  4]],

       [[ 5,  6,  7]],

       [[ 2,  3,  5]]])

In [73]:
f.dtype

dtype('int64')

In [74]:
type(f)

numpy.ndarray

In [76]:
f.ndim

3

In [77]:
#3D Array:
z = np.array([[[1, 2, 3]], [[4, 5, 6]], 
                            [[6, 7, 8]],[[9, 5, 4]]
                            ])
z

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[6, 7, 8]],

       [[9, 5, 4]]])

In [78]:
z.ndim

3

In [79]:
z.size

12

In [80]:
len(z)

4

In [81]:
z.shape

(4, 1, 3)

In [82]:
z.dtype

dtype('int64')

In [87]:
z2 = z.reshape((6, 2))
z2

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7],
       [8, 9],
       [5, 4]])

In [88]:
# Indexing & Slicing:
f = np.array([1, 2, 3, 4])
f

array([1, 2, 3, 4])

In [90]:
f[1]

np.int64(2)

In [91]:
f[0:2]

array([1, 2])

In [93]:
f[1: ]

array([2, 3, 4])

In [94]:
f[-1:]

array([4])

In [100]:
f[-2: -1]

array([3])

In [101]:
b = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
b.ndim

2

In [103]:
b[0]

array([1, 2, 3])

In [104]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
b[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
b[-1:]

array([[7, 8, 9]])

In [107]:
b[-1:, 1:]

array([[8, 9]])

In [108]:
b[b<2]

array([1])

In [109]:
b[b>2]

array([3, 4, 5, 6, 7, 8, 9])

In [110]:
b[b%2 == 0]

array([2, 4, 6, 8])

In [111]:
#Use the Conditions:
c = b[(b>2) & (b<4)]
c

array([3])

In [112]:
x = b[(b>2) & (b<5)]
x

array([3, 4])

In [113]:
y = b[(b>2) & (b<5) & (b%2==0)]
y

array([4])

In [115]:
k = b[(b>2) | (b<5)]
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# Range of Sets
a = np.arange(0, 225, 5)

In [119]:
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [120]:
arr = a[30: 45]

In [121]:
arr

array([150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210,
       215, 220])

In [123]:
#Stack of Array (Horizantal, Vartical)
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10 , 11, 12])
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [124]:
k = np.hstack((a, b))
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
d = c.reshape(2, 6)
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [129]:
# Create the Matrixs:
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
c = np.arange(2, 100, 5)
c

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [142]:
k = c.reshape(2, 10)
k

array([[ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [52, 57, 62, 67, 72, 77, 82, 87, 92, 97]])

In [145]:
c.min()

np.int64(2)

In [146]:
c.max()

np.int64(97)

In [147]:
c.sum()

np.int64(990)

In [148]:
f = np.array([[1, 2, 3], [3, 4, 6]])

In [149]:
f

array([[1, 2, 3],
       [3, 4, 6]])

In [150]:
f.min()

np.int64(1)

In [151]:
f.max()

np.int64(6)

In [152]:
f.sum()

np.int64(19)

In [154]:
f+np.array([7, 8, 9])

array([[ 8, 10, 12],
       [10, 12, 15]])

In [157]:
k = np.vstack((f, np.array([4, 7, 8])))
k

array([[1, 2, 3],
       [3, 4, 6],
       [4, 7, 8]])

In [158]:
# By flip:
np.flip(f)

array([[6, 4, 3],
       [3, 2, 1]])

In [161]:
m = np.arange(0, 20, 2)
m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [163]:
m.reshape(5, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [167]:
#Transpose:
L = m.T
L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [169]:
I = L.T

In [170]:
I

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [174]:
np.ones((4, 5, 1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [177]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [178]:
a.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [179]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])